AR scene logo + border + reticle
Dev-Dawgz/scavenjourneys pull request #91
Opened 2023-10-31 22:41 UTC by yeauxdejuan

2023-10-31 22:48 UTC, nasthia861 commented on client/components/ARSteps.tsx
delete all references to video element

2023-10-31 22:48 UTC, nasthia861 requested changes
video element no longer needed

2023-10-31 22:55 UTC, yeauxdejuan commented on client/components/ARSteps.tsx
adjusted.

2023-10-31 23:31 UTC, ddmcdona06 approved these changes

2023-11-01 15:14 UTC, nasthia861 approved these changes

2023-11-01 15:15 UTC, merged